// Oleksii Kovalenko telegram - @traewe

import { StyleSheet, Dimensions } from "react-native";

// Coefficients for transmitting sizes from Figma to user's device
const screenHeight = Dimensions.get("screen").height;
const screenWidth = Dimensions.get("screen").width;
const figmaHeightPixelConverter = screenHeight / 648;
const figmaWidthPixelConverter = screenWidth / 356;

export const styles = StyleSheet.create({
  linearGradient: {
    opacity: 0.7,
    top: 0,
    position: "absolute",
    left: 0,
    right: 0,
    height: Dimensions.get("screen").height,
    width: Dimensions.get("screen").width,
  },
  settingOption: {
    width: 0.9 * screenWidth,
    height: 0.07 * screenHeight,
    backgroundColor: "white",
    borderRadius: 9,
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "center",
    zIndex: 1,
    overflow: "hidden",
  },
  binIconContainer: {
    position: "absolute",
    right: 0.045 * screenWidth,
  },
  binIcon: {
    width: 0.05 * screenWidth,
    height: 0.05 * screenHeight,
  },
  roleAvatarInList: {
    width: 0.045 * screenHeight,
    height: 0.045 * screenHeight,
    borderRadius: 100,
    position: "absolute",
    left: 0.0125 * screenHeight,
    alignItems: "center",
    justifyContent: "center",
  },
  roleTitleContainer: {
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    flexDirection: "row",
    position: "absolute",
    left: -0.2 * screenWidth,
  },
  roleTitleInList: {
    fontFamily: "JacquesFrancois-Regular",
    fontSize: 20,
    color: "rgb(43, 29, 29)",
  },
  doneButtonContainer: {
    position: "absolute",
    top: 0.058 * screenHeight,
    right: 0,
    width: 0.2 * screenWidth,
  },
  doneButtonTitle: {
    fontSize: 21,
    fontFamily: "JacquesFrancois-Regular",
    color: "rgb(43, 29, 29)",
  },
  containerForSettingTitle: {
    top: 0.04 * screenHeight,
    width: 0.9 * screenWidth,
    height: 0.04 * screenHeight,
    justifyContent: "center",
    alignSelf: "center",
  },
  settingTitle: {
    fontFamily: "JacquesFrancois-Regular",
    fontSize: 20,
    color: "rgb(43, 29, 29)",
  },
  newRoleNameInput: {
    width: "90%",
    fontSize: 17,
    fontFamily: "JacquesFrancois-Regular",
    color: "rgb(43, 29, 29)",
  },
  settingOptionTitle: {
    position: "absolute",
    left: 0.05 * screenWidth,
    fontFamily: "JacquesFrancois-Regular",
    fontSize: 20,
    color: "rgb(43, 29, 29)",
  },
  settingOptionRightArrow: {
    position: "absolute",
    right: 0.045 * screenWidth,
    width: 11 * figmaWidthPixelConverter,
    height: 17 * figmaWidthPixelConverter,
    color: "rgb(111, 111, 111)",
  },
  roleAppearanceContainer: {
    top: 0.04 * screenHeight,
    left: 0.05 * screenWidth,
    width: 0.9 * screenWidth,
    height: 0.07 * screenHeight,
    backgroundColor: "white",
    borderRadius: 9,
    justifyContent: "flex-start",
    alignItems: "center",
    flexDirection: "row",
    alignSelf: "flex-start",
    overflow: "hidden",
  },
  roleTitle: {
    fontSize: 17,
    fontFamily: "JacquesFrancois-Regular",
    color: "rgb(43, 29, 29)",
  },
  roleTitleContainerWhileCreating: {
    position: "absolute",
    left: 0.09 * screenWidth + 22 * figmaWidthPixelConverter,
    width: "65%",
    justifyContent: "center",
  },
  topToolBar: {
    backgroundColor: "rgb(231, 230,	228)",
    width: "100%",
    alignItems: "center",
    height: 77 * figmaHeightPixelConverter,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 37,
    borderBottomRightRadius: 37,
    borderWidth: 1.5,
    borderColor: "rgb(161, 156, 145)",
    justifyContent: "center",
  },
  searchInChatContainer: {
    width: 0.63 * screenWidth,
    height: 0.05 * screenHeight,
    borderRadius: 40,
    backgroundColor: "rgb(39, 39, 39)",
    top: 0.012 * screenHeight,
    left: -0.05 * screenWidth,
    justifyContent: "center",
    paddingLeft: 0.02 * screenWidth,
  },
  contactNameInput: {
    width: "90%",
    fontSize: 17,
    fontFamily: "JacquesFrancois-Regular",
    color: "rgb(136, 130, 130)",
  },
  contactsTitleContainer: {
    justifyContent: "center",
    top: 0.027 * screenHeight,
  },
  contactsTitle: {
    fontFamily: "JacquesFrancois-Regular",
    color: "rgb(39, 39, 39)",
    fontSize: 20,
  },
  contactContainer: {
    width: screenWidth,
    height: 0.055 * screenHeight,
    justifyContent: "center",
    borderTopWidth: 0.2,
    borderBottomWidth: 0.2,
  },
  contactAvatarInList: {
    width: 0.045 * screenHeight,
    height: 0.045 * screenHeight,
    borderRadius: 100,
    position: "absolute",
    left: 0.0125 * screenHeight,
    alignItems: "center",
    justifyContent: "center",
  },
  contactTitleContainer: {
    position: "absolute",
    left: 0.09 * screenWidth + 22 * figmaWidthPixelConverter,
    width: "70%",
    justifyContent: "center",
  },
  contactTitleInList: {
    fontFamily: "JacquesFrancois-Regular",
    fontSize: 18,
  },
  contactCheckMarkContainer: {
    position: "absolute",
    backgroundColor: "rgb(254, 224, 163)",
    borderRadius: 100,
    width: 0.06 * screenWidth,
    height: 0.06 * screenWidth,
    borderWidth: 0.2,
    right: 0.0125 * screenHeight,
    justifyContent: "center",
    alignItems: "center",
  },
  checkmarkIcon: {
    width: 0.037 * screenWidth,
    height: 0.037 * screenWidth,
  },
  avatarInList: {
    width: 0.045 * screenHeight,
    height: 0.045 * screenHeight,
    borderRadius: 100,
    position: "absolute",
    left: 0.0125 * screenHeight,
    alignItems: "center",
    justifyContent: "center",
  },
  plusIcon: {
    position: "absolute",
    left: 0.045 * screenWidth,
    width: 22 * figmaWidthPixelConverter,
    height: 22 * figmaWidthPixelConverter,
  },
  plusRoleTitle: {
    position: "absolute",
    left: 0.09 * screenWidth + 22 * figmaWidthPixelConverter,
    fontFamily: "JacquesFrancois-Regular",
    fontSize: 20,
    color: "rgb(43, 29, 29)",
  },
});
