// Oleksii Kovalenko telegram - @traewe

import { StyleSheet, Dimensions } from "react-native";

// Coefficients for transmitting sizes from Figma to user's device
const screenHeight = Dimensions.get("screen").height;
const screenWidth = Dimensions.get("screen").width;
const figmaHeightPixelConverter = screenHeight / 648;
const figmaWidthPixelConverter = screenWidth / 356;

export const styles = StyleSheet.create({
  linearGradient: {
    top: 0,
    position: "absolute",
    left: 0,
    right: 0,
    height: screenHeight,
    width: screenWidth,
  },
  blurEffect: {
    width: "100%",
    height: "100%",
    position: "absolute",
    zIndex: 1,
  },
  avatarMainContainer: {
    width: screenWidth,
    height: 0.5 * screenHeight,
  },
  profileTitle: {
    fontSize: 27,
    fontFamily: "JacquesFrancois-Regular",
    color: "white",
    zIndex: 1,
  },
  goBackContainer: {
    width: "100%",
    alignItems: "center",
    height: 77 * figmaHeightPixelConverter,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 37,
    borderBottomRightRadius: 37,
    borderWidth: 1.5,
    borderColor: "transparent",
    justifyContent: "center",
    zIndex: 2,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    top: -77 * figmaHeightPixelConverter,
    zIndex: 1,
  },
  userInfoMainContainer: {
    width: 0.75 * screenWidth,
    height: 0.159 * screenHeight,
    alignSelf: "center",
    top: 18.5 * figmaHeightPixelConverter,
    justifyContent: "center",
    alignItems: "center",
  },
  infoView: {
    width: "80%",
    height: 0.053 * screenHeight,
    paddingLeft: 0.01 * screenWidth,
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 0.018 * screenWidth,
  },
  infoTitle: {
    fontSize: 17,
    fontFamily: "Rubik-Regular",
    color: "rgba(255, 255, 255, 1)",
  },
  separatingVerticalLine: {
    height: "80%",
    width: 0.7,
    backgroundColor: "rgba(255, 255, 255, 0.57)",
  },
  separatingHorizontalLine: {
    width: "100%",
    alignSelf: "center",
    borderBottomWidth: 0.7,
    borderColor: "rgba(255, 255, 255, 0.57)",
  },
  currentAvatarBarMainContainer: {
    flexDirection: "row",
    height: 3,
    width: 0.7 * screenWidth,
    backgroundColor: "transparent",
    zIndex: 3,
    position: "absolute",
    top: 40,
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 17,
  },
  avatarBarElement: { height: "100%", position: "absolute", borderRadius: 17 },
  opacityToSeeNextPhoto: {
    width: 0.65 * screenWidth,
    height: 0.5 * screenHeight,
    zIndex: 2,
    position: "absolute",
    alignSelf: "flex-end",
  },
  opacityToSeePreviousPhoto: {
    width: 0.35 * screenWidth,
    height: 0.4 * screenHeight,
    top: 0.1 * screenHeight,
    zIndex: 2,
    position: "absolute",
    alignSelf: "flex-start",
  },
  additionalOpacityToSeePreviousPhoto: {
    width: 0.2 * screenWidth,
    height: 0.1 * screenHeight,
    left: 0.15 * screenWidth,
    zIndex: 2,
    position: "absolute",
    alignSelf: "flex-start",
  },
  containerForAnimatedMessage: {
    backgroundColor: "white",
    width: 0.6 * screenWidth,
    height: 0.05 * screenHeight,
    left: 0.2 * screenWidth,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 25,
    borderWidth: 0.5,
    borderColor: "rgb(161, 156, 145)",
    flexDirection: "row",
  },
  animatedMessageText: {
    fontSize: 17,
    fontFamily: "JacquesFrancois-Regular",
  },
  copyIcon: {
    width: 20 * figmaWidthPixelConverter,
    height: 20 * figmaWidthPixelConverter,
    color: "black",
  },
  callingMenuMainContainer: {
    position: "absolute",
    width: 0.8 * screenWidth,
    height: 0.235 * screenHeight,
    top: 0.3 * screenHeight,
    right: 0.1 * screenWidth,
    borderRadius: 20,
    borderWidth: 0.5,
    overflow: "hidden",
    flexDirection: "column",
    zIndex: 1,
  },
  phoneNumberContainer: {
    justifyContent: "center",
    alignItems: "center",
    height: "31%",
    backgroundColor: "white",
  },
  phoneNumberTitle: { fontFamily: "JacquesFrancois-Regular", fontSize: 17 },
  callingMenuOptionContainer: {
    backgroundColor: "white",
    height: 0.05405 * screenHeight,
    borderTopWidth: 0.5,
    justifyContent: "center",
    alignItems: "center",
  },
  callingMenuOptionTitle: {
    fontFamily: "JacquesFrancois-Regular",
    color: "rgb(124, 79, 145)",
    fontSize: 16,
  },
  callingMenuCancelButton: {
    position: "absolute",
    width: 0.6 * screenWidth,
    alignSelf: "center",
    height: 0.05 * screenHeight,
    backgroundColor: "white",
    justifyContent: "center",
    alignItems: "center",
    top: 0.55 * screenHeight,
    borderRadius: 17,
    zIndex: 1,
  },
});
