interface Message {
  id: number;
  type: string;
  text: string;
  timeStamp: number;
  isUser: boolean;
  isReply: boolean;
  replyMessageID?: number; // Необов'язкове поле, оскільки не завжди присутнє
  edited: boolean;
}

let messages:Message[] = [
  {
    id: 1,
    type: 'text',
    text: '1. Hello aboba, Denis pisyun sosav smachnyi tomu vin i schaslyviy gandon',
    timeStamp: Date.now(), 
    isUser: false,
    isReply: false,
    edited: false,
  },
  {
    id: 2,
    type: 'text',
    text: '2. Pisya',
    timeStamp: Date.now(),
    isUser: true,
    isReply: true,
    edited: false,
    replyMessageID: 1,
  },
  {
    id: 3,
    type: 'text',
    text: '3. Hello aboba',
    timeStamp: Date.now(),
    isUser: false,
    isReply: false,
    edited: false,
  },
  {
    id: 4,
    type: 'text',
    text: '4. Bimbom',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 5,
    type: 'text',
    text: '5. Pisya',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 6,
    type: 'text',
    text: '6. Hello aboba',
    timeStamp: Date.now(), 
    isUser: false,
    isReply: true,
    edited: false,
    replyMessageID: 4,
  },
  {
    id: 7,
    type: 'text',
    text: '7. Bimbom',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 8,
    type: 'text',
    text: '8. Hello aboba',
    timeStamp: Date.now(),
    isUser: false,
    isReply: false,
    edited: false,
  },
  {
    id: 9,
    type: 'text',
    text: '9. Pisya',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 10,
    type: 'text',
    text: '10. Bimbom',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 11,
    type: 'text',
    text: '11. Hello aboba',
    timeStamp: Date.now(), 
    isUser: false,
    isReply: false,
    edited: false,
  },
  {
    id: 12,
    type: 'text',
    text: '12. Pisya',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 13,
    type: 'text',
    text: '13. Hello aboba',
    timeStamp: Date.now(),
    isUser: false,
    isReply: false,
    edited: false,
  },
  {
    id: 14,
    type: 'text',
    text: '14. Bimbomka',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 15,
    type: 'text',
    text: '15. Pisya',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 16,
    type: 'text',
    text: '16. Hello aboba',
    timeStamp: Date.now(), 
    isUser: false,
    isReply: false,
    edited: false,
  },
  {
    id: 17,
    type: 'text',
    text: '17. PisyaPisyaPisyaPisyaPisya PisyaPisyaPisyaPisyaPisyaPisyaPisya'
    +'PisyaPisyaPisya PisyaPisyaPisyaPisyaPisyaPisyaPisyaPisyaPisyaPisya'
    +'PisyaPisyaPisyaPisyaPisya PisyaPisyaPisyaPisyaPisyaPisyaPisyaPisya'
    +'PisyaPisyaPisyaPisyaPisyaPisyaPisyaPisyaPisyaPisyaPisyaPisyaPisya'
    +'PisyaPisyaPisya PisyaPisyaPisya PisyaPisyaPisyaPisyaPisya PisyaPisya'
    +'PisyaPisyaPisya PisyaPisyaPisyaPisyaPisya PisyaPisyaPisyaPisyaPisya'
    +'PisyaPisyaPisyaPisyaPisyaPisya PisyaPisyaPisyaPisyaPisyaPisyaPisya',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 18,
    type: 'text',
    text: '18. Hello aboba',
    timeStamp: Date.now(),
    isUser: false,
    isReply: false,
    edited: false,
  },
  {
    id: 19,
    type: 'text',
    text: '19. Pisya',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 20,
    type: 'text',
    text: '20. Pisya',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 21,
    type: 'text',
    text: '21. Hello aboba',
    timeStamp: Date.now(), 
    isUser: false,
    isReply: false,
    edited: false,
  },
  {
    id: 22,
    type: 'text',
    text: '22. Pisya',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 23,
    type: 'text',
    text: '23. Hello aboba',
    timeStamp: Date.now(),
    isUser: false,
    isReply: false,
    edited: false,
  },
  {
    id: 24,
    type: 'text',
    text: '24. Pisya',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 25,
    type: 'text',
    text: '25. Pisya',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 26,
    type: 'text',
    text: '26. Hello aboba',
    timeStamp: Date.now(), 
    isUser: false,
    isReply: false,
    edited: false,
  },
  {
    id: 27,
    type: 'text',
    text: '27. Pisya',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 28,
    type: 'text',
    text: '28. Hello aboba',
    timeStamp: Date.now(),
    isUser: false,
    isReply: false,
    edited: false,
  },
  {
    id: 29,
    type: 'text',
    text: '29. Alya ulyu',
    timeStamp: Date.now(),
    isUser: true,
    isReply: false,
    edited: false,
  },
  {
    id: 30,
    type: 'text',
    text: '30. Sho ty?',
    timeStamp: Date.now(),
    isUser: true,
    isReply: true,
    edited: false,
    replyMessageID: 14
  },
  {
    id: 31,
    type: 'text',
    text: '31. ?',
    timeStamp: Date.now(),
    isUser: true,
    isReply: true,
    edited: false,
    replyMessageID: 17
  },
  {
    id: 32,
    type: 'text',
    text: '32. nigger',
    timeStamp: Date.now(),
    isUser: true,
    isReply: true,
    edited: false,
    replyMessageID: 17
  }
];

export {Message, messages};