export interface countryProps {
  label: string;
  phone: string;
  code: string;
  phoneLength?: number | number[];
  min?: number;
  max?: number;
  suggested?: boolean;
}

export const countryNameRecord = {
  AF: "Afghanistan",
  AL: "Albania",
  DZ: "Algeria",
  AS: "American Samoa",
  AD: "Andorra",
  AO: "Angola",
  AI: "Anguilla",
  AQ: "Antarctica",
  AG: "Antigua and Barbuda",
  AR: "Argentina",
  AM: "Armenia",
  AW: "Aruba",
  AU: "Australia",
  AT: "Austria",
  AZ: "Azerbaijan",
  BS: "Bahamas",
  BH: "Bahrain",
  BD: "Bangladesh",
  BB: "Barbados",
  BY: "Belarus",
  BE: "Belgium",
  BZ: "Belize",
  BJ: "Benin",
  BM: "Bermuda",
  BT: "Bhutan",
  BO: "Bolivia",
  BA: "Bosnia and Herzegovina",
  BW: "Botswana",
  BV: "Bouvet Island",
  BR: "Brazil",
  IO: "British Indian Ocean Territory",
  BN: "Brunei",
  BG: "Bulgaria",
  BF: "Burkina Faso",
  BI: "Burundi",
  KH: "Cambodia",
  CM: "Cameroon",
  CA: "Canada",
  CV: "Cape Verde",
  KY: "Cayman Islands",
  CF: "Central African Republic",
  TD: "Chad",
  CL: "Chile",
  CN: "China",
  CX: "Christmas Island",
  CC: "Cocos (Keeling) Islands",
  CO: "Colombia",
  KM: "Comoros",
  CG: "Congo",
  CK: "Cook Islands",
  CR: "Costa Rica",
  HR: "Croatia",
  CU: "Cuba",
  CY: "Cyprus",
  CZ: "Czech Republic",
  DK: "Denmark",
  DJ: "Djibouti",
  DM: "Dominica",
  DO: "Dominican Republic",
  TP: "East Timor",
  EC: "Ecuador",
  EG: "Egypt",
  SV: "El Salvador",
  GQ: "Equatorial Guinea",
  ER: "Eritrea",
  EE: "Estonia",
  ET: "Ethiopia",
  FK: "Falkland Islands",
  FO: "Faroe Islands",
  FJ: "Fiji Islands",
  FI: "Finland",
  FR: "France",
  GF: "French Guiana",
  PF: "French Polynesia",
  TF: "French Southern territories",
  GA: "Gabon",
  GM: "Gambia",
  GE: "Georgia",
  DE: "Germany",
  GH: "Ghana",
  GI: "Gibraltar",
  GR: "Greece",
  GL: "Greenland",
  GD: "Grenada",
  GP: "Guadeloupe",
  GU: "Guam",
  GT: "Guatemala",
  GG: "Guernsey",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  GY: "Guyana",
  HT: "Haiti",
  HM: "Heard Island and McDonald Islands",
  VA: "Holy See (Vatican City State)",
  HN: "Honduras",
  HK: "Hong Kong",
  HU: "Hungary",
  IS: "Iceland",
  IN: "India",
  ID: "Indonesia",
  IR: "Iran",
  IQ: "Iraq",
  IE: "Ireland",
  IM: "Isle of Man",
  IL: "Israel",
  IT: "Italy",
  CI: "Ivory Coast",
  JM: "Jamaica",
  JP: "Japan",
  JE: "Jersey",
  JO: "Jordan",
  KZ: "Kazakhstan",
  KE: "Kenya",
  KI: "Kiribati",
  KW: "Kuwait",
  KG: "Kyrgyzstan",
  LA: "Laos",
  LV: "Latvia",
  LB: "Lebanon",
  LS: "Lesotho",
  LR: "Liberia",
  LY: "Libyan Arab Jamahiriya",
  LI: "Liechtenstein",
  LT: "Lithuania",
  LU: "Luxembourg",
  MO: "Macao",
  MK: "North Macedonia",
  MG: "Madagascar",
  MW: "Malawi",
  MY: "Malaysia",
  MV: "Maldives",
  ML: "Mali",
  MT: "Malta",
  MH: "Marshall Islands",
  MQ: "Martinique",
  MR: "Mauritania",
  MU: "Mauritius",
  YT: "Mayotte",
  MX: "Mexico",
  FM: "Micronesia, Federated States of",
  MD: "Moldova",
  MC: "Monaco",
  MN: "Mongolia",
  ME: "Montenegro",
  MS: "Montserrat",
  MA: "Morocco",
  MZ: "Mozambique",
  MM: "Myanmar",
  NA: "Namibia",
  NR: "Nauru",
  NP: "Nepal",
  NL: "Netherlands",
  NC: "New Caledonia",
  NZ: "New Zealand",
  NI: "Nicaragua",
  NE: "Niger",
  NG: "Nigeria",
  NU: "Niue",
  NF: "Norfolk Island",
  KP: "North Korea",
  GB: "United Kingdom of Great Britain and Northern Ireland",
  MP: "Northern Mariana Islands",
  NO: "Norway",
  OM: "Oman",
  PK: "Pakistan",
  PW: "Palau",
  PS: "Palestine",
  PA: "Panama",
  PG: "Papua New Guinea",
  PY: "Paraguay",
  PE: "Peru",
  PH: "Philippines",
  PN: "Pitcairn",
  PL: "Poland",
  PT: "Portugal",
  PR: "Puerto Rico",
  QA: "Qatar",
  RE: "Reunion",
  RO: "Romania",
  RU: "Russian Federation",
  RW: "Rwanda",
  SH: "Saint Helena",
  KN: "Saint Kitts and Nevis",
  LC: "Saint Lucia",
  PM: "Saint Pierre and Miquelon",
  VC: "Saint Vincent and the Grenadines",
  WS: "Samoa",
  SM: "San Marino",
  ST: "Sao Tome and Principe",
  SA: "Saudi Arabia",
  SN: "Senegal",
  RS: "Serbia",
  SC: "Seychelles",
  SL: "Sierra Leone",
  SG: "Singapore",
  SK: "Slovakia",
  SI: "Slovenia",
  SB: "Solomon Islands",
  SO: "Somalia",
  ZA: "South Africa",
  GS: "South Georgia and the South Sandwich Islands",
  KR: "South Korea",
  SS: "South Sudan",
  ES: "Spain",
  LK: "Sri Lanka",
  SD: "Sudan",
  SR: "Suriname",
  SJ: "Svalbard and Jan Mayen",
  SZ: "Swaziland",
  SE: "Sweden",
  CH: "Switzerland",
  SY: "Syria",
  TJ: "Tajikistan",
  TZ: "Tanzania",
  TH: "Thailand",
  CD: "The Democratic Republic of Congo",
  TL: "Timor-Leste",
  TG: "Togo",
  TK: "Tokelau",
  TO: "Tonga",
  TT: "Trinidad and Tobago",
  TN: "Tunisia",
  TR: "Turkey",
  TM: "Turkmenistan",
  TC: "Turks and Caicos Islands",
  TV: "Tuvalu",
  UG: "Uganda",
  UA: "Ukraine",
  AE: "United Arab Emirates",
  US: "United States",
  UM: "United States Minor Outlying Islands",
  UY: "Uruguay",
  UZ: "Uzbekistan",
  VU: "Vanuatu",
  VE: "Venezuela",
  VN: "Vietnam",
  VG: "Virgin Islands, British",
  VI: "Virgin Islands, U.S.",
  WF: "Wallis and Futuna",
  EH: "Western Sahara",
  YE: "Yemen",
  ZM: "Zambia",
  ZW: "Zimbabwe",
} as const;
export const countryList: countryProps[] = [
  { code: "AF", label: "Afghanistan", phone: "93", phoneLength: 9 },
  { code: "AL", label: "Albania", phone: "355", phoneLength: 9 },
  { code: "DZ", label: "Algeria", phone: "213", phoneLength: 9 },
  { code: "AX", label: "Alland Islands", max: 10, min: 7, phone: "358" },
  { code: "AS", label: "American Samoa", phone: "1-684", phoneLength: 10 },
  { code: "AD", label: "Andorra", phone: "376", phoneLength: 6 },
  { code: "AO", label: "Angola", phone: "244", phoneLength: 9 },
  { code: "AI", label: "Anguilla", phone: "1-264", phoneLength: 10 },
  { code: "AQ", label: "Antarctica", phone: "672", phoneLength: 6 },
  { code: "AG", label: "Antigua and Barbuda", phone: "1-268", phoneLength: 10 },
  { code: "AR", label: "Argentina", phone: "54", phoneLength: [6, 7, 8] },
  { code: "AM", label: "Armenia", phone: "374", phoneLength: 6 },
  { code: "AW", label: "Aruba", phone: "297", phoneLength: 7 },
  {
    code: "AU",
    label: "Australia",
    phone: "61",
    phoneLength: 9,
    suggested: true,
  },
  { code: "AT", label: "Austria", phone: "43", phoneLength: [10, 11] },
  { code: "AZ", label: "Azerbaijan", phone: "994", phoneLength: 9 },
  { code: "BS", label: "Bahamas", phone: "1-242", phoneLength: 10 },
  { code: "BH", label: "Bahrain", phone: "973", phoneLength: 8 },
  { code: "BD", label: "Bangladesh", phone: "880", phoneLength: 10 },
  { code: "BB", label: "Barbados", phone: "1-246", phoneLength: 10 },
  { code: "BY", label: "Belarus", phone: "375", phoneLength: 9 },
  { code: "BE", label: "Belgium", phone: "32", phoneLength: 9 },
  { code: "BZ", label: "Belize", phone: "501", phoneLength: 7 },
  { code: "BJ", label: "Benin", phone: "229", phoneLength: 8 },
  { code: "BM", label: "Bermuda", phone: "1-441", phoneLength: 10 },
  { code: "BT", label: "Bhutan", phone: "975", phoneLength: 7 },
  { code: "BO", label: "Bolivia", phone: "591", phoneLength: 9 },
  { code: "BA", label: "Bosnia and Herzegovina", phone: "387", phoneLength: 8 },
  { code: "BW", label: "Botswana", phone: "267", phoneLength: 7 },
  { code: "BV", label: "Bouvet Island", phone: "47", phoneLength: 10 },
  { code: "BR", label: "Brazil", phone: "55", phoneLength: 11 },
  {
    code: "IO",
    label: "British Indian Ocean Territory",
    phone: "246",
    phoneLength: 7,
  },
  {
    code: "VG",
    label: "British Virgin Islands",
    phone: "1-284",
    phoneLength: 7,
  },
  { code: "BN", label: "Brunei Darussalam", phone: "673", phoneLength: 7 },
  { code: "BG", label: "Bulgaria", phone: "359", phoneLength: 9 },
  { code: "BF", label: "Burkina Faso", phone: "226", phoneLength: 8 },
  { code: "BI", label: "Burundi", phone: "257", phoneLength: 8 },
  { code: "KH", label: "Cambodia", phone: "855", phoneLength: 9 },
  { code: "CM", label: "Cameroon", phone: "237", phoneLength: 9 },
  { code: "CA", label: "Canada", phone: "1", phoneLength: 10, suggested: true },
  { code: "CV", label: "Cape Verde", phone: "238", phoneLength: 7 },
  { code: "KY", label: "Cayman Islands", phone: "1-345", phoneLength: 7 },
  {
    code: "CF",
    label: "Central African Republic",
    phone: "236",
    phoneLength: 8,
  },
  { code: "TD", label: "Chad", phone: "235", phoneLength: 6 },
  { code: "CL", label: "Chile", phone: "56", phoneLength: 9 },
  { code: "CN", label: "China", phone: "86", phoneLength: 11 },
  { code: "CX", label: "Christmas Island", phone: "61", phoneLength: 9 },
  {
    code: "CC",
    label: "Cocos (Keeling) Islands",
    phone: "61",
    phoneLength: 10,
  },
  { code: "CO", label: "Colombia", phone: "57", phoneLength: 10 },
  { code: "KM", label: "Comoros", phone: "269", phoneLength: 7 },
  {
    code: "CD",
    label: "Congo, Democratic Republic of the",
    phone: "243",
    phoneLength: 7,
  },
  { code: "CG", label: "Congo, Republic of the", phone: "242", phoneLength: 9 },
  { code: "CK", label: "Cook Islands", phone: "682", phoneLength: 5 },
  { code: "CR", label: "Costa Rica", phone: "506", phoneLength: 8 },
  { code: "CI", label: "Cote d'Ivoire", phone: "225", phoneLength: 8 },
  { code: "HR", label: "Croatia", phone: "385", phoneLength: 9 },
  { code: "CU", label: "Cuba", phone: "53", phoneLength: 8 },
  { code: "CW", label: "Curacao", phone: "599", phoneLength: 7 },
  { code: "CY", label: "Cyprus", phone: "357", phoneLength: 8 },
  { code: "CZ", label: "Czech Republic", phone: "420", phoneLength: 9 },
  { code: "DK", label: "Denmark", phone: "45", phoneLength: 8 },
  { code: "DJ", label: "Djibouti", phone: "253", phoneLength: 10 },
  { code: "DM", label: "Dominica", phone: "1-767", phoneLength: 10 },
  { code: "DO", label: "Dominican Republic", phone: "1-809", phoneLength: 10 },
  { code: "EC", label: "Ecuador", phone: "593", phoneLength: 9 },
  { code: "EG", label: "Egypt", phone: "20", phoneLength: 10 },
  { code: "SV", label: "El Salvador", phone: "503", phoneLength: 8 },
  { code: "GQ", label: "Equatorial Guinea", phone: "240", phoneLength: 9 },
  { code: "ER", label: "Eritrea", phone: "291", phoneLength: 7 },
  { code: "EE", label: "Estonia", phone: "372", phoneLength: 8 },
  { code: "ET", label: "Ethiopia", phone: "251", phoneLength: 9 },
  {
    code: "FK",
    label: "Falkland Islands (Malvinas)",
    phone: "500",
    phoneLength: 5,
  },
  { code: "FO", label: "Faroe Islands", phone: "298", phoneLength: 5 },
  { code: "FJ", label: "Fiji", phone: "679", phoneLength: 7 },
  { code: "FI", label: "Finland", max: 11, min: 9, phone: "358" },
  { code: "FR", label: "France", phone: "33", phoneLength: 9, suggested: true },
  { code: "GF", label: "French Guiana", phone: "594", phoneLength: 9 },
  { code: "PF", label: "French Polynesia", phone: "689", phoneLength: 8 },
  {
    code: "TF",
    label: "French Southern Territories",
    phone: "262",
    phoneLength: 10,
  },
  { code: "GA", label: "Gabon", phone: "241", phoneLength: 7 },
  { code: "GM", label: "Gambia", phone: "220", phoneLength: 7 },
  { code: "GE", label: "Georgia", phone: "995", phoneLength: 9 },
  {
    code: "DE",
    label: "Germany",
    phone: "49",
    phoneLength: 10,
    suggested: true,
  },
  { code: "GH", label: "Ghana", phone: "233", phoneLength: 9 },
  { code: "GI", label: "Gibraltar", phone: "350", phoneLength: 8 },
  { code: "GR", label: "Greece", phone: "30", phoneLength: 10 },
  { code: "GL", label: "Greenland", phone: "299", phoneLength: 6 },
  { code: "GD", label: "Grenada", phone: "1-473", phoneLength: 10 },
  { code: "GP", label: "Guadeloupe", phone: "590", phoneLength: 9 },
  { code: "GU", label: "Guam", phone: "1-671", phoneLength: 10 },
  { code: "GT", label: "Guatemala", phone: "502", phoneLength: 8 },
  { code: "GG", label: "Guernsey", phone: "44", phoneLength: 10 },
  { code: "GN", label: "Guinea", phone: "224", phoneLength: 9 },
  { code: "GW", label: "Guinea-Bissau", phone: "245", phoneLength: 9 },
  { code: "GY", label: "Guyana", phone: "592", phoneLength: 7 },
  { code: "HT", label: "Haiti", phone: "509", phoneLength: 8 },
  {
    code: "HM",
    label: "Heard Island and McDonald Islands",
    phone: "672",
    phoneLength: 10,
  },
  {
    code: "VA",
    label: "Holy See (Vatican City State)",
    phone: "379",
    phoneLength: 10,
  },
  { code: "HN", label: "Honduras", phone: "504", phoneLength: 8 },
  { code: "HK", label: "Hong Kong", phone: "852", phoneLength: 8 },
  { code: "HU", label: "Hungary", phone: "36", phoneLength: 9 },
  { code: "IS", label: "Iceland", phone: "354", phoneLength: 7 },
  { code: "IN", label: "India", phone: "91", phoneLength: 10 },
  { code: "ID", label: "Indonesia", phone: "62", phoneLength: 11 },
  {
    code: "IR",
    label: "Iran, Islamic Republic of",
    phone: "98",
    phoneLength: 11,
  },
  { code: "IQ", label: "Iraq", phone: "964", phoneLength: 10 },
  { code: "IE", label: "Ireland", phone: "353", phoneLength: 9 },
  { code: "IM", label: "Isle of Man", phone: "44", phoneLength: 10 },
  { code: "IL", label: "Israel", phone: "972", phoneLength: 9 },
  { code: "IT", label: "Italy", phone: "39", phoneLength: 10 },
  { code: "JM", label: "Jamaica", phone: "1-876", phoneLength: 10 },
  { code: "JP", label: "Japan", phone: "81", suggested: true },
  { code: "JE", label: "Jersey", phone: "44", phoneLength: 10 },
  { code: "JO", label: "Jordan", phone: "962", phoneLength: [8, 9] },
  { code: "KZ", label: "Kazakhstan", phone: "7", phoneLength: 10 },
  { code: "KE", label: "Kenya", phone: "254", phoneLength: 10 },
  { code: "KI", label: "Kiribati", phone: "686", phoneLength: 8 },
  {
    code: "KP",
    label: "Korea, Democratic People's Republic of",
    phone: "850",
    phoneLength: [4, 6, 7, 13],
  },
  { code: "KR", label: "Korea, Republic of", phone: "82", phoneLength: [7, 8] },
  { code: "XK", label: "Kosovo", phone: "383", phoneLength: 8 },
  { code: "KW", label: "Kuwait", phone: "965", phoneLength: 8 },
  { code: "KG", label: "Kyrgyzstan", phone: "996", phoneLength: 9 },
  {
    code: "LA",
    label: "Lao People's Democratic Republic",
    phone: "856",
    phoneLength: [8, 9],
  },
  { code: "LV", label: "Latvia", phone: "371", phoneLength: 8 },
  { code: "LB", label: "Lebanon", phone: "961", phoneLength: [7, 8] },
  { code: "LS", label: "Lesotho", phone: "266", phoneLength: 8 },
  { code: "LR", label: "Liberia", phone: "231", phoneLength: [8, 9] },
  { code: "LY", label: "Libya", phone: "218", phoneLength: 10 },
  { code: "LI", label: "Liechtenstein", phone: "423", phoneLength: 7 },
  { code: "LT", label: "Lithuania", phone: "370", phoneLength: 8 },
  { code: "LU", label: "Luxembourg", phone: "352", phoneLength: 9 },
  { code: "MO", label: "Macao", phone: "853", phoneLength: 8 },
  {
    code: "MK",
    label: "Macedonia, the Former Yugoslav Republic of",
    phone: "389",
    phoneLength: 8,
  },
  { code: "MG", label: "Madagascar", phone: "261", phoneLength: 7 },
  { code: "MW", label: "Malawi", phone: "265", phoneLength: [7, 8, 9] },
  { code: "MY", label: "Malaysia", phone: "60", phoneLength: 7 },
  { code: "MV", label: "Maldives", phone: "960", phoneLength: 7 },
  { code: "ML", label: "Mali", phone: "223", phoneLength: 8 },
  { code: "MT", label: "Malta", phone: "356", phoneLength: 8 },
  { code: "MH", label: "Marshall Islands", phone: "692", phoneLength: 7 },
  { code: "MQ", label: "Martinique", phone: "596", phoneLength: 9 },
  { code: "MR", label: "Mauritania", phone: "222", phoneLength: 8 },
  { code: "MU", label: "Mauritius", phone: "230", phoneLength: 8 },
  { code: "YT", label: "Mayotte", phone: "262", phoneLength: 9 },
  { code: "MX", label: "Mexico", phone: "52", phoneLength: 10 },
  {
    code: "FM",
    label: "Micronesia, Federated States of",
    phone: "691",
    phoneLength: 7,
  },
  { code: "MD", label: "Moldova, Republic of", phone: "373", phoneLength: 8 },
  { code: "MC", label: "Monaco", phone: "377", phoneLength: 8 },
  { code: "MN", label: "Mongolia", phone: "976", phoneLength: 8 },
  { code: "ME", label: "Montenegro", phone: "382", phoneLength: 8 },
  { code: "MS", label: "Montserrat", phone: "1-664", phoneLength: 10 },
  { code: "MA", label: "Morocco", phone: "212", phoneLength: 9 },
  { code: "MZ", label: "Mozambique", phone: "258", phoneLength: 12 },
  { code: "MM", label: "Myanmar", max: 10, min: 7, phone: "95" },
  { code: "NA", label: "Namibia", phone: "264", phoneLength: 7 },
  { code: "NR", label: "Nauru", phone: "674", phoneLength: 7 },
  { code: "NP", label: "Nepal", phone: "977", phoneLength: 10 },
  { code: "NL", label: "Netherlands", phone: "31", phoneLength: 9 },
  { code: "NC", label: "New Caledonia", phone: "687", phoneLength: 6 },
  { code: "NZ", label: "New Zealand", phone: "64", phoneLength: [8, 9] },
  { code: "NI", label: "Nicaragua", phone: "505", phoneLength: 8 },
  { code: "NE", label: "Niger", phone: "227", phoneLength: 8 },
  { code: "NG", label: "Nigeria", phone: "234", phoneLength: 8 },
  { code: "NU", label: "Niue", phone: "683", phoneLength: 4 },
  { code: "NF", label: "Norfolk Island", phone: "672", phoneLength: 6 },
  {
    code: "MP",
    label: "Northern Mariana Islands",
    phone: "1-670",
    phoneLength: 7,
  },
  { code: "NO", label: "Norway", phone: "47", phoneLength: 8 },
  { code: "OM", label: "Oman", phone: "968", phoneLength: 8 },
  { code: "PK", label: "Pakistan", phone: "92", phoneLength: 10 },
  { code: "PW", label: "Palau", phone: "680", phoneLength: 7 },
  { code: "PS", label: "Palestine, State of", phone: "970", phoneLength: 9 },
  { code: "PA", label: "Panama", phone: "507", phoneLength: 8 },
  { code: "PG", label: "Papua New Guinea", phone: "675", phoneLength: 8 },
  { code: "PY", label: "Paraguay", phone: "595", phoneLength: 9 },
  { code: "PE", label: "Peru", phone: "51", phoneLength: 9 },
  { code: "PH", label: "Philippines", phone: "63", phoneLength: 10 },
  { code: "PN", label: "Pitcairn", phone: "870", phoneLength: 9 },
  { code: "PL", label: "Poland", phone: "48", phoneLength: 9 },
  { code: "PT", label: "Portugal", phone: "351", phoneLength: 9 },
  { code: "PR", label: "Puerto Rico", phone: "1", phoneLength: 10 },
  { code: "QA", label: "Qatar", phone: "974", phoneLength: 8 },
  { code: "RE", label: "Reunion", phone: "262", phoneLength: 10 },
  { code: "RO", label: "Romania", phone: "40", phoneLength: 10 },
  { code: "RU", label: "Russian Pederation", phone: "7", phoneLength: 10 },
  { code: "RW", label: "Rwanda", phone: "250", phoneLength: 9 },
  { code: "BL", label: "Saint Barthelemy", phone: "590", phoneLength: 9 },
  { code: "SH", label: "Saint Helena", phone: "290", phoneLength: 4 },
  {
    code: "KN",
    label: "Saint Kitts and Nevis",
    phone: "1-869",
    phoneLength: 10,
  },
  { code: "LC", label: "Saint Lucia", phone: "1-758", phoneLength: 7 },
  {
    code: "MF",
    label: "Saint Martin (French part)",
    phone: "590",
    phoneLength: 6,
  },
  {
    code: "PM",
    label: "Saint Pierre and Miquelon",
    phone: "508",
    phoneLength: 6,
  },
  {
    code: "VC",
    label: "Saint Vincent and the Grenadines",
    phone: "1-784",
    phoneLength: 7,
  },
  { code: "WS", label: "Samoa", phone: "685", phoneLength: [5, 6, 7] },
  { code: "SM", label: "San Marino", phone: "378", phoneLength: 10 },
  { code: "ST", label: "Sao Tome and Principe", phone: "239", phoneLength: 7 },
  { code: "SA", label: "Saudi Arabia", phone: "966", phoneLength: 9 },
  { code: "SN", label: "Senegal", phone: "221", phoneLength: 9 },
  { code: "RS", label: "Serbia", phone: "381", phoneLength: 9 },
  { code: "SC", label: "Seychelles", phone: "248", phoneLength: 7 },
  { code: "SL", label: "Sierra Leone", phone: "232", phoneLength: 8 },
  { code: "SG", label: "Singapore", phone: "65", phoneLength: 8 },
  {
    code: "SX",
    label: "Sint Maarten (Dutch part)",
    phone: "1-721",
    phoneLength: 10,
  },
  { code: "SK", label: "Slovakia", phone: "421", phoneLength: 9 },
  { code: "SI", label: "Slovenia", phone: "386", phoneLength: 9 },
  { code: "SB", label: "Solomon Islands", phone: "677", phoneLength: 7 },
  { code: "SO", label: "Somalia", phone: "252", phoneLength: [8, 9] },
  { code: "ZA", label: "South Africa", phone: "27", phoneLength: 9 },
  {
    code: "GS",
    label: "South Georgia and the South Sandwich Islands",
    phone: "500",
    phoneLength: 5,
  },
  { code: "SS", label: "South Sudan", phone: "211", phoneLength: 7 },
  { code: "ES", label: "Spain", phone: "34", phoneLength: 9 },
  { code: "LK", label: "Sri Lanka", phone: "94", phoneLength: 7 },
  { code: "SD", label: "Sudan", phone: "249", phoneLength: 7 },
  { code: "SR", label: "Suriname", phone: "597", phoneLength: [6, 7] },
  { code: "SJ", label: "Svalbard and Jan Mayen", phone: "47", phoneLength: 8 },
  { code: "SZ", label: "Swaziland", phone: "268", phoneLength: 8 },
  { code: "SE", label: "Sweden", phone: "46", phoneLength: 7 },
  { code: "CH", label: "Switzerland", phone: "41", phoneLength: 9 },
  { code: "SY", label: "Syrian Arab Republic", phone: "963", phoneLength: 7 },
  {
    code: "TW",
    label: "Taiwan, Province of China",
    phone: "886",
    phoneLength: 9,
  },
  { code: "TJ", label: "Tajikistan", phone: "992", phoneLength: 9 },
  { code: "TH", label: "Thailand", phone: "66", phoneLength: 9 },
  { code: "TL", label: "Timor-Leste", phone: "670", phoneLength: 7 },
  { code: "TG", label: "Togo", phone: "228", phoneLength: 8 },
  { code: "TK", label: "Tokelau", phone: "690", phoneLength: 5 },
  { code: "TO", label: "Tonga", phone: "676", phoneLength: 5 },
  { code: "TT", label: "Trinidad and Tobago", phone: "1-868", phoneLength: 7 },
  { code: "TN", label: "Tunisia", phone: "216", phoneLength: 8 },
  { code: "TR", label: "Turkey", phone: "90", phoneLength: 11 },
  { code: "TM", label: "Turkmenistan", phone: "993", phoneLength: 8 },
  {
    code: "TC",
    label: "Turks and Caicos Islands",
    phone: "1-649",
    phoneLength: 10,
  },
  { code: "TV", label: "Tuvalu", phone: "688", phoneLength: 5 },
  { code: "UG", label: "Uganda", phone: "256", phoneLength: 7 },
  { code: "UA", label: "Ukraine", phone: "380", phoneLength: 9 },
  { code: "AE", label: "United Arab Emirates", phone: "971", phoneLength: 9 },
  { code: "GB", label: "United Kingdom", phone: "44", phoneLength: 10 },
  {
    code: "TZ",
    label: "United Republic of Tanzania",
    phone: "255",
    phoneLength: 7,
  },
  {
    code: "US",
    label: "United States",
    phone: "1",
    phoneLength: 10,
    suggested: true,
  },
  { code: "UY", label: "Uruguay", phone: "598", phoneLength: 8 },
  { code: "VI", label: "US Virgin Islands", phone: "1-340", phoneLength: 10 },
  { code: "UZ", label: "Uzbekistan", phone: "998", phoneLength: 9 },
  { code: "VU", label: "Vanuatu", phone: "678", phoneLength: 5 },
  { code: "VE", label: "Venezuela", phone: "58", phoneLength: 7 },
  { code: "VN", label: "Vietnam", phone: "84", phoneLength: 9 },
  { code: "WF", label: "Wallis and Futuna", phone: "681", phoneLength: 6 },
  { code: "EH", label: "Western Sahara", phone: "212", phoneLength: 9 },
  { code: "YE", label: "Yemen", phone: "967", phoneLength: 9 },
  { code: "ZM", label: "Zambia", phone: "260", phoneLength: 9 },
  { code: "ZW", label: "Zimbabwe", phone: "263", phoneLength: 9 },
];
//console.log(countryList.sort((a, b) => a.label.localeCompare(b.label)));

//console.log(countryList.findIndex((country:countryProps)=>{ return country.code=="AX"}))
export type CountryCode = keyof typeof countryNameRecord;
